config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope(:user) { unauthenticated { root to: 'home#index' } }

  root 'stocks#index'

  resources :stocks
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
# frozen_string_literal: true

class Stock < ApplicationRecord
  MIN_NAME_LENGTH = 3
  MAX_NAME_LENGTH = 20

  MIN_YEARS = 0
  MAX_YEARS = 100

  MIN_UNIT_PRICE = 0

  MIN_INTEREST = 0
  MAX_INTEREST = 1

  belongs_to :user, inverse_of: :stocks

  validates :name, presence: true, length: { minimum: MIN_NAME_LENGTH, maximum: MAX_NAME_LENGTH }

  validates :unit_price, presence: true, numericality: { greater_than: MIN_UNIT_PRICE }

  validates :interest, presence:     true,
                       numericality: { greater_than:          MIN_INTEREST,
                                       less_than_or_equal_to: MAX_INTEREST }

  validates :duration, presence:     true,
                       numericality: { greater_than: MIN_YEARS, less_than_or_equal_to: MAX_YEARS }

  scope :in_historic_for_user, ->(user_id) { where(user_id: user_id).order(created_at: :desc) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stocks, inverse_of: :user, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :authenticate_user!
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
# frozen_string_literal: true

class StocksController < ApplicationController
  decorates_assigned :interest

  def index
    @facade = ::Stocks::IndexFacade.new(params: params, user: current_user)
  end

  def show
    @facade = ::Stocks::ShowFacade.new(stock_id: params[:id])
  end

  def new
    @stock = Stock.new
  end

  def create
    @stock = ::Stocks::Create.call(user: current_user, params: stock_params)

    return render :new unless @stock.valid?

    redirect_to root_path, notice: I18n.t('stocks.create.successfully_created')
  end

  def destroy
    ::Stocks::Destroy.call(stock_id: params[:id])

    redirect_to root_path, notice: I18n.t('stocks.index.successfully_deleted')
  end

  private

  def stock_params
    params.require(:stock).permit(:name, :unit_price, :interest, :duration)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :require_no_authentication, only: %i[new create cancel], if: :current_user

    protected

    def require_no_authentication
      redirect_to root_path, alert: t('devise.failure.already_authenticated')
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/layouts_helper.rb
# frozen_string_literal: true

module LayoutsHelper
  BACK_LINK = 'javascript:history.back()'

  def controller_stylesheet_link_tag
    stylesheet_link_tag ::Assets::General.call(css_params)
  end

  def controller_script_include_tag(**options)
    javascript_include_tag ::Assets::General.call(js_params), options
  end

  def action_stylesheet_link_tag
    stylesheet_link_tag ::Assets::Action.call(css_params)
  end

  def action_script_include_tag(**options)
    javascript_include_tag ::Assets::Action.call(js_params), options
  end

  def page_title
    return controller_title unless I18n.exists?(action_page_title_key)

    t('page_title', title: t(action_page_title_key))
  end

  private

  def css_params
    {
      type:       :css,
      controller: current_controller,
      action:     current_action
    }
  end

  def js_params
    {
      type:       :js,
      controller: current_controller,
      action:     current_action
    }
  end

  def current_controller
    exception? ? controller_name : params[:controller]
  end

  def current_action
    return action_name if exception?
    return :new        if action_name.inquiry.create?
    return :edit       if action_name.inquiry.update?

    params[:action]
  end

  def exception?
    controller_name.inquiry.exceptions?
  end

  def action_page_title_key
    "#{controller_path}.#{current_action}.title"
  end

  def controller_page_title_key
    "#{controller_path}.title"
  end

  def controller_title
    t(
      'page_title',
      title:  t(controller_page_title_key, default: t('default_page_title'))
    )
  end

  def controller_path
    current_controller.tr('/', '.')
  end
end

app/views/home/_register.html.haml
#register.card.bg-light.border-0
  %article.card-body.mx-auto{ style: 'max-width: 400px;' }
    %h4.card-title.mt-3.text-center= t('home.index.create_button')
    %p.text-center= t('home.index.get_started')
    = simple_form_for(:user, url: user_registration_path) do |f|
      = f.error_notification
      .form-group.input-group
        .input-group-prepend
          %span.input-group-text
            %i.fa.fa-envelope
        = f.input :email, label: false, required: true, autofocus: true, class: 'form-control', placeholder: 'Email'
      .form-group.input-group
        .input-group-prepend
          %span.input-group-text
            %i.fa.fa-lock
        = f.input :password, label: false, required: true, class: 'form-control', placeholder: 'Password'
      .form-group.input-group
        .input-group-prepend
          %span.input-group-text
            %i.fa.fa-lock
        = f.input :password_confirmation, label: false, required: true, class: 'form-control', placeholder: 'Repeat password'
      .form-group
        = f.submit t('home.index.create_button'), class: 'btn btn-primary btn-block'
      %p.divider-text
        %span.bg-light OR
      %a.form-group.js-switch-form
        .btn.btn-info.btn-block
          = t('home.index.already_registered')

app/views/home/_sign_in.html.haml
#sign-in.card.bg-light.border-0
  %article.card-body.mx-auto
    %h4.card-title.mt-3.text-center= t('home.index.sign_in')
    = simple_form_for(:user, url: user_session_path) do |f|
      .form-group.input-group
        .input-group-prepend
          %span.input-group-text
            %i.fa.fa-envelope
        = f.input :email, label: false, required: false, autofocus: true, class: 'form-control', placeholder: 'Email'
      .form-group.input-group
        .input-group-prepend
          %span.input-group-text
            %i.fa.fa-lock
        = f.input :password, label: false, required: false, class: 'form-control', placeholder: 'Password'
      .form-group.input-group
        = f.input :remember_me, as: :boolean
      .form-group
        = f.submit 'Sign in', class: 'btn btn-primary btn-block'
        %p.divider-text
          %span.bg-light= t('home.index.or')
      %a.form-group.js-switch-form
        .btn.btn-info.btn-block
          = t('home.index.no_account')

app/views/home/index.html.haml
.container-fluid.bg-light
  #homepage.row.justify-content-center
    .col-4.js-register-form
      = render 'register'
    .col-4.d-none.js-sign-in-form
      = render 'sign_in'

app/views/layouts/_flash.html.haml
#flash-container{ data: { flash: flash.to_h.to_json } }

app/views/layouts/_navigation.html.haml
#page-top
  %nav.navbar.navbar-expand.navbar-dark.bg-dark.static-top.justify-content-between
    = link_to t('layouts.navbar.root_link'), root_path, class: '.navbar-brand.mr-1'

    - if current_user.present?
      %ul.navbar-nav.ml-auto.ml-md-0
        %li.nav-item.dropdown.no-arrow
          %a#userDropdown.nav-link.dropdown-toggle{ 'aria-expanded': 'false', 'aria-haspopup': 'true', 'data-toggle': 'dropdown', href: '#', role: 'button' }
            %i.fas.fa-user-circle.fa-fw
          .dropdown-menu.dropdown-menu-right{'aria-labelledby': 'userDropdown'}
            %a.dropdown-item{ 'data-target': '#logoutModal', 'data-toggle': 'modal', href: '#' }= t('layouts.navbar.log_out')

app/views/layouts/application.html.haml
!!!

%html
  %head
    %title= yield(:title).presence || page_title

    = favicon_link_tag 'favicon.ico'

    = stylesheet_link_tag 'application', media: :all
    = stylesheet_pack_tag 'main'

    = controller_stylesheet_link_tag
    = action_stylesheet_link_tag

    = javascript_pack_tag 'application'
    = javascript_include_tag 'application'

    = controller_script_include_tag data: { turbolinks_track: :reload }
    = action_script_include_tag     data: { turbolinks_track: :reload }

    = csrf_meta_tags

  %body
    = render 'layouts/navigation'
    = render 'layouts/flash'

    .content
      = yield

app/views/pagy/_nav.html.haml
-# This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
-# calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").
-# The link variable is set to a proc that returns the link tag.
-# Usage: link.call( page_number [, text [, extra_attributes_string ]])
- link = pagy_link_proc(pagy, 'class="page-link"')

%nav.pagy-nav-bootstrap.pagination{ 'aria-label': 'pager', role: 'navigation' }
  %ul.pagination
    - if pagy.prev
      %li.page-item.prev!= link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"')
    - else
      %li.page-item.prev.disabled
        %a.page-link{ href: '#' }!= pagy_t('pagy.nav.prev')
    - pagy.series.each do |item|                      # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]
      - if item.is_a?(Integer)                        # page link
        %li.page-item!= link.call(item)
      - elsif item.is_a?(String)                      # current page
        %li.page-item.active!= link.call(item)
      - elsif item == :gap                            # page gap
        %li.page-item.disabled.gap
          %a.page-link{ href: '#' }!= pagy_t('pagy.nav.gap')

    - if pagy.next
      %li.page-item.next!= link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"')
    - else
      %li.page-item.next.disabled
        %a.page-link{ href: '#' }!= pagy_t('pagy.nav.next')

app/views/stocks/index.html.haml
#wrapper
  #content-wrapper
    .container-fluid
      / Breadcrumbs
      %ol.breadcrumb
        %li.breadcrumb-item
          %a{href: '#'} Dashboard
        %li.breadcrumb-item.active Overview
      / Icon Cards
      .row
        .col-xl-3.col-sm-6.mb-3
          = link_to new_stock_path do
            .card.text-white.bg-primary.o-hidden.h-100
              .card-body
                .card-body-icon
                  %i.fas.fa-plus-circle
                .mr-5= t('stocks.index.create_stock')
      / Area Chart Example
      - if @facade.stocks.any?
        .card.mb-3
          .card-header
            %i.fas.fa-chart-area
            = link_to t('home.index.last_stock'), stock_path(@facade.first_stock)

          = render 'stocks/index/chart', chart_params: @facade.first_stock_chart_params

          .card-footer.small.text-muted= t('stocks.index.last_update', date: @facade.last_update)
        / DataTables Example
        .card.mb-3
          .card-header
            %i.fas.fa-table
            = t('stocks.index.your_stocks')

          = render 'stocks/index/table', facade: @facade if @facade.stocks

          .card-footer.small.text-muted= t('stocks.index.last_update', date: @facade.last_update)

#logoutModal.modal.fade{ 'aria-hidden': 'true', 'aria-labelledby': 'exampleModalLabel', role: 'dialog', tabindex: '-1' }
  .modal-dialog{ role: 'document' }
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title= t('modal.logout.ready_to_leave')
        %button.close{ 'aria-label': 'Close', 'data-dismiss': 'modal', type: 'button' }
          %span{'aria-hidden': 'true'} ×
      .modal-body= t('modal.logout.logout')
      .modal-footer
        %button.btn.btn-secondary{ 'data-dismiss': 'modal', type: 'button' }= t('modal.logout.cancel')
        = link_to t('layouts.navbar.log_out'), destroy_user_session_path, method: :delete, class: 'btn btn-primary'

app/views/stocks/index/_chart.html.haml
.card-body
  = column_chart(chart_params, id: 'chart', prefix: '$', xtitle: 'Years')

app/views/stocks/index/_item.html.haml
%tr
  %td.text-center= index
  %td
    = link_to item.name, stock_path(item)
  %td= item.unit_price
  %td= item.humanized_interest
  %td= item.duration
  %td.td-actions.text-center
    = link_to stock_path(item), class: 'mr-2 show-link' do
      %i.fa.fa-search

    = link_to stock_path(item), class: 'delete-link', method: :delete do
      %i.fas.fa-trash-alt

app/views/stocks/index/_table.html.haml
.card-body
  .table-responsive
    %table#dataTable.table.table-bordered{cellspacing: '0', width: '100%'}
      %thead
        %tr
          %th.text-center #
          %th= t('records.stock.properties.name')
          %th= t('records.stock.properties.unit_price')
          %th= t('records.stock.properties.interest')
          %th= t('records.stock.properties.duration')
          %th.text-center= t('stocks.index.actions')
      %tbody
        - facade.stocks.each.with_index(facade.page_counter) do |item, index|
          = render partial: 'stocks/index/item', locals: { item: item, index: index }

    = render 'pagy/nav', pagy: facade.pagination

app/views/stocks/new.html.haml
.container
  .row.justify-content-center.mt-5
    .create-form
      = simple_form_for(@stock) do |form|
        = form.input :name, input_html: { minlength: 3, maxlength: 20 }
        = form.input :unit_price, input_html: { min: 1 }
        = form.input :interest, input_html: { min: 1, max: 100 }
        = form.input :duration, input_html: { min: 1 }
        = form.button :submit, class: 'w-100'

app/views/stocks/show.html.haml
.container
  .row
    = render 'stocks/show/item',  facade: @facade

    = render 'stocks/show/chart', facade: @facade

app/views/stocks/show/_chart.html.haml
.col-9
  = column_chart(facade.chart_params, id: 'chart', prefix: '$', xtitle: 'Years')

app/views/stocks/show/_item.html.haml
#container.col-3
  #accordion
    .card-header
      %a.card-link{ 'data-toggle': 'collapse', href: '#collapseSecond' }
        %h5.card-subtitle.mb-2.text-center= facade.stock_name
    #collapseSECOND.collapse.show{ 'data-parent': '#accordion' }
      .card-body
        %table.table.table-hover.group.table-striped
          %table.table.table-hover.group.table-striped
            %tbody
              %tr
                %td= t('records.stock.properties.name')
                %td= facade.stock_name
              %tr
                %td= t('stocks.show.properties.unit_price')
                %td= facade.stock_unit_price
              %tr
                %td= t('stocks.show.properties.interest')
                %td= facade.stock_humanized_interest
              %tr
                %td= t('stocks.show.properties.duration')
                %td= facade.stock_duration
          .card-footer.text-muted